version: '3'
services:
  to-do-app:
    build: .
    ports:
      - "3000:3000"
    # volumes:
    #   - ./:/usr/src/app
    #   - /usr/src/app/node_modules
    environment:
      - PORT=3000
    # env_file:
    #   - ./.env